# Generated by Django 5.2.4 on 2025-08-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_category_alter_task_options_task_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="task",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
        migrations.DeleteModel(
            name="TaskComment",
        ),
    ]
